### ISSUE TITLE
cista::get_if<>(const& v) missing cista::index_of_type<> ctor call

### ISSUE THREAD

**Issue by ChemistAion** [felixguendling/cista#101]
One more thing here - on return it should be called `cista::index_of_type<T, Ts...>()` <- missing **"()"**
https://github.com/felixguendling/cista/blob/da8da3a596550bfa22563d56dbcea04155fb42bf/include/cista/containers/variant.h#L402-L408

_Originally posted by @ChemistAion in https://github.com/felixguendling/cista/issues/98#issuecomment-881584940_

**Comment by felixguendling** [comment]
Current version has this?

https://github.com/felixguendling/cista/blob/fc45eaaa34887e6bb5d8b22a6a54140726e6328a/include/cista/containers/variant.h#L402-L408

Fixed here: https://github.com/felixguendling/cista/commit/eb050ae7602dbf8d0b5f9c9023d8d41b2d2ce4b3

**Comment by ChemistAion** [comment]
Perfect!
_Schönes Wochenende!_

**Comment by felixguendling** [comment]
No problem.

_Ebenso!_ :)
