### ISSUE TITLE
Possible compile-time speed improvements for arity calculation...

### ISSUE THREAD

**Issue by ChemiaAion** [felixguendling/cista#11]
Hi,

I have investigated arity calculations more deeply lately and I think I found much a simpler and elegant way than one implemented here as [Björn Fahller](https://playfulprogramming.blogspot.com/2016/12/serializing-structs-with-c17-structured.html) idea.

It ts this one: ["aggregate arity"](https://codereview.stackexchange.com/questions/142804/get-n-th-data-member-of-a-struct) by Anatoliy V. Tomilov, @tomilov.

Of course it still does not handles arity for non-aggregates as struct-binding will do, but this is known "issue" - goes the same for Björn's implementation.

It is fully SFINAE-automatic (no macros) with std::declval's from non-static _wildcard_, and additionally - most important - it could be quite easily extended by relatively simple logic for log_time-like arity calculations, you could find examples/ideas of this in the links listed in my gist attached below.

So, here is my current approach: ["ChemiaAion arity"](https://gist.github.com/ChemiaAion/4118a3598f0b120b7f9c5884e9799a8b)
You could also find a little refactored Björn's implementation there for a reference.

**I think you should consider this alternative approach for compile-time speed optimizations.**

**Comment by ChemiaAion** [comment]
Ahh, one more thing: I have added there `constexpr std::size_t Arity()` to get arity as `std::size_t` with a [fallback](https://gist.github.com/ChemiaAion/4118a3598f0b120b7f9c5884e9799a8b#file-arity-hpp-L42-L47) to reject all non-aggregate/inherited etc. for which IMO we should implement `static_assert(arity != 0, "Please implement custom serializer.");` or some other kind of custom-inherited-arity field to handle this case.

For the note:
You could also play here a little bit more than with Björn's apporach - just replace the return value with a raw `return Detail::ArityImpl<Aggregate>().size();`.
This will give you _all the time_ a constructible Aggregate with at least <0, 1> arity depends on _wildcard_ features, make no sense IMO but it handles more (as constructible) than Björn's apporach.

**Comment by felixguendling** [comment]
Hi, thank you for your suggestion! 👍 

I've adopted your version:
https://github.com/felixguendling/cista/blob/724c484ff2e851ecda58141eefc75ae37b29355f/include/cista/reflection/arity.h

I moved the check `is_aggregate & is_standard_layout & is_polymorphic` to the `serialize` function because these properties are not required to iterate members (that's possible a `std::string` member, too - but it's not for `std::string` itself):
https://github.com/felixguendling/cista/blob/724c484ff2e851ecda58141eefc75ae37b29355f/include/cista/serialization.h#L48-L51

**Comment by ChemiaAion** [comment]
Perfect!
