### ISSUE TITLE
Failure on empty structures

### ISSUE THREAD

**Issue by edmcman** [felixguendling/cista#110]
https://onlinegdb.com/Tn9IxpYdE

**Comment by felixguendling** [comment]
Can you please try it with the current version?
I would guess that it works with the latest version of Cista.

**Comment by edmcman** [comment]
Ah, you are right!  I used the link in the README to download, which points to version 0.7.

Thank you!

**Comment by felixguendling** [comment]
Oh! Thank you very much for this info. Will fix it!
