### ISSUE TITLE
Bug with inheritance and static data members

### ISSUE THREAD

**Issue by edmcman** [felixguendling/cista#111]
The following program
``` c++
#include <iostream>
#include "cista.h"

struct a {
    static int x;
    int z;
    CISTA_PRINTABLE(a)
};

struct b : public a {
    int y;
    CISTA_PRINTABLE(b)
};

int main() {
  b instance;
  std::cout << instance;
  // "{1, 2, 100, hello}"
}

int a::x = 42;
```

yields the following error for me:
```
~/Downloads $ clang++-9 -std=c++2a bah.cc -o bah                                                                                                                  16:27:20
In file included from bah.cc:2:
./cista.h:2149:11: error: cannot decompose class type 'b': both it and its base class 'a' have non-static data members
    auto& [p1, p2] = t;
          ^
./cista.h:3734:58: note: in instantiation of function template specialization 'cista::to_tuple<const b>' requested here
    std::apply([&](auto&&... args) { (fn(args), ...); }, to_tuple(t));
                                                         ^
bah.cc:12:5: note: in instantiation of function template specialization 'cista::for_each_field<const b, (lambda at bah.cc:12:5)>' requested here
    CISTA_PRINTABLE(b)
    ^
./cista.h:6381:14: note: expanded from macro 'CISTA_PRINTABLE'
    ::cista::for_each_field(o, [&](auto&& f) {                              \
             ^
1 error generated.
```

I would like to use cista in a project where there is a lot of inheritance and static members, so this is a problem.  I don't know enough about [] binding and templating to know if there is a way to work around this, or if it's a more fundamental limitation.

**Comment by edmcman** [comment]
Oh, and I am using 0.8 this time ;)

**Comment by felixguendling** [comment]
Unfortunately, I don't know how to overcome the C++ limitations in this regard (structured binding inherited classes).

Would it help you, if there was a macro for this case or a method you could override?

```
#include <iostream>
#include "cista.h"

struct a {
    static int x;
    int z;
    auto cista_members() noexcept const { return std::make_tuple(x, z); } // NEW
    CISTA_PRINTABLE(a)
};

struct b : public a {
    int y;
    auto cista_members() noexcept const { return std::make_tuple(x, z, y); } // NEW
    CISTA_PRINTABLE(b)
};

int main() {
  b instance;
  std::cout << instance;
  // "{1, 2, 100, hello}"
}

int a::x = 42;
```

Maybe this could something that I could make work. Would this help you?

**Comment by edmcman** [comment]
This would be helpful!  It would be even nicer if the derived classes did not have to specify their inherited members, but that is not a big deal.

**Comment by felixguendling** [comment]
I started working on it in #112
It's not ready yet but the basic idea seems to work.

**Comment by felixguendling** [comment]
#112 is merged now.

Example usage: https://github.com/felixguendling/cista/blob/d320baca2da83a7c4c78198d842eca1b4b35d851/test/cista_members_test.cc#L42-L47

**Comment by edmcman** [comment]
Awesome, I will try this out today.  Thanks!

**Comment by edmcman** [comment]
Seems to be working pretty well!  The only problem I had was that cista_members is inherited by children (which of course makes sense in retrospect) so it always has to be overridden.  Also, I noticed none of your tests inherit any members.

**Comment by felixguendling** [comment]
Yes, I don't know how to fix that you may forget to override. Inheritance always also propagates the `cista_member` method.

I added a test with inheriting members: https://github.com/felixguendling/cista/blob/c3ff21d317cbe214c7e1a2efb5cca72ac7cf32ac/test/cista_members_test.cc#L55-L71

Thank you for this hint. I had to fix something to make serialization work in this case. Now, it should be fine.
