### ISSUE TITLE
MSVC and Clang Win32 Support

### ISSUE THREAD

**Issue by Hun1eR** [felixguendling/cista#123]
When I tried to compile a win32 project I got `bit_counting.h(94,35): error C3861: _mm_popcnt_u64: identifier not found`
This is because win32 doesn't support _mm_popcnt_**u64** only _mm_popcnt_**u32**

Clang compiler (windows) doesn't support booth _mm_popcnt_u64 and _mm_popcnt_u32.

I suppose this can be replaced with [__popcnt](https://docs.microsoft.com/en-us/cpp/intrinsics/popcnt16-popcnt-popcnt64) which is supported by MSVC and Сlang

**Comment by felixguendling** [comment]
This should work now on master with #124. Thank you for your help!
