### ISSUE TITLE
All types decays should be strengthened to std::remove_reference_t<std::remove_cv_t<>>

### ISSUE THREAD

**Issue by ChemiaAion** [felixguendling/cista#13]
Hi,

I noticed that all types decays are formed as: `std::remove_reference_t<std::remove_const_t<>>`;

This seems to be enough for almost all current use cases, besides `sizeof(std::declval<>)`:
`std::is_scalar_v<>` is happy with cv qualifiers, i.e.: it gives the same answer for all cv combinations;
`std::is_pointer_v<>` removes cv qualifiers, so it is happy;
`std::alignment_of_v<>` is happy;
`std::numeric_limits<>` are happy;
`sizeof(std::declval<>)` I would be somehow careful here, since returned `std::add_rvalue_reference<>` could be problematic (impossible types) when used with const/volatile qualifiers, details: [LWG2101](https://cplusplus.github.io/LWG/issue2101);

I would recommend to strength all types decays as `std::remove_reference_t<std::remove_cv_t<>>`;

**Comment by felixguendling** [comment]
Thank you for pointing this out. I have introduced a new utility:
https://github.com/felixguendling/cista/blob/f18411f7e5e5d2814dcb0594933f75a9e28ca96e/include/cista/decay.h#L1-L10

That's now in use everywhere. I think this should help.

**Comment by ChemiaAion** [comment]
I forgot that we have one more thing to handle: `std::reference_wrapper<>`, this guy will pass a reference under the radar of 'std::remove_reference_t<>';
Please take a look on my gist for related snippets: [Type Reference Decay Tryouts](https://gist.github.com/ChemiaAion/05fa1c4477fa0524ac8f93b5ce36d077)

Please improve the `decay_t` utility by `std::reference_wrapper<>` dedicated decay layer, something like `DecayReferenceWrapper` from my gist.
