### ISSUE TITLE
Ser/Des-ialize does not rebuild ptrs etc. - an another day with namespaces

### ISSUE THREAD

**Issue by ChemistAion** [felixguendling/cista#139]
Please take a look on this example: https://wandbox.org/permlink/l2iEAmTpiCWFtLb6

Works like a charm, i.e.: `CISTA::vector<CISTA::ptr<ElementTest>> paths_` pointers are perfectly rebuild during deserialization.
No issue...

Exactly same stuff under latest VS 17.2.6 with all features beyond C++20 enabled gives me two things:
* static_assert need for a custom serializer for `ElementTest` - whereas wandbox not;
* after ser/des empty fn provided for `ElementTest`, paths_ still points to memory _before_ serialization;

I am still investigating this...

**Comment by felixguendling** [comment]
First question: are you using the latest release or the latest master commit of cista?

**Comment by felixguendling** [comment]
Cannot reproduce with MSVC.
https://godbolt.org/z/EMzj9EfYo

Or did I miss something?

**Comment by ChemistAion** [comment]
Sourced through "Download" button on: https://cista.rocks/

**Comment by ChemistAion** [comment]
...working on this now

**Comment by ChemistAion** [comment]
...some more time needed, closing for now

**Comment by felixguendling** [comment]
Let me know when you find a reproducible code.
For our uses on MSVC [here](https://github.com/motis-project/motis), it seems to work fine until now.

**Comment by ChemistAion** [comment]
OK, I have some time now...
I have an example (MSVC native with latest stuff), but it is deeply embedded into my working project:
![serdes_issue_showcase001](https://user-images.githubusercontent.com/12657534/182706318-d7e450d0-70a8-4543-bd1d-03509ca8bdc7.png)

Working now to strip it down...
...my bet is that I am using additional layer of `namespace`, `using` and `auto` to access CISTA features, we will see

**Comment by ChemistAion** [comment]
Virtually the same ex. from:
> Cannot reproduce with MSVC. https://godbolt.org/z/EMzj9EfYo (just copy&pasted the whole `cista.h` there instead of `#include "cista.h"`)
> 
> Or did I miss something?

[STEP1] https://godbolt.org/z/WE8WTbGr9
Introduction of `namespace TEST` will lead to series of my mistakes? ;)
```
    namespace TEST
    {
        struct VEC2
        {
            float                                   x, y;
            constexpr VEC2()                      : x(0.0f), y(0.0f) { }
            constexpr VEC2(float _x, float _y)    : x(_x), y(_y) { }
        };
    }
```

**Comment by felixguendling** [comment]
> to implement these dummy/empty serdes

This is not the right way to do it. If you add custom constructor or do something that removes the C++ aggregate property, you need to take care for serializing all members on your own. Having an empty body does not work in this case!

This makes your bug reproducible: https://godbolt.org/z/q5Ghd7Pd5

You need to implement a proper serialize and deserialize method, calling serialize/deserialize properly for all members.

If you opt-out of "cista is doing everything for you automatically" and implement your own stuff, it's your responsibility to not miss any member. Having custom (de-)serialization functions is very error-prone.

Here's the program with proper (de-)serialization for the `ElementTest` type. Don't forget to adapt it if you add/remove members!

https://godbolt.org/z/81TWKojzv

```cpp
    template <typename Context>
	inline void serialize(Context& context, const ElementTest* test, const cista::offset_t offset) {
        using cista::serialize;
        serialize(context, &test->node_, offset + offsetof(ElementTest, node_));
        serialize(context, &test->paths_, offset + offsetof(ElementTest, paths_));
    }

    template <typename Context>
	inline void deserialize(const Context& context, ElementTest* test) {
        using cista::deserialize;
        deserialize(context, &test->node_);
        deserialize(context, &test->paths_);
    }
```

**Comment by ChemistAion** [comment]
You have been too fast: https://godbolt.org/z/jvrTzKd37

**Comment by ChemistAion** [comment]
...yep, now it is obvious - thx for your time!
As an example here - you should consider to add some more adv. docu sections? ;)

**Comment by felixguendling** [comment]
Yep, thank you for the hint. I'll put a similar example + explanation in the docs.

**Comment by felixguendling** [comment]
Added a section to this Wiki page:
https://github.com/felixguendling/cista/wiki/Custom-(De-)Serialization-Functions

**Comment by ChemistAion** [comment]
To show you exactly why I ended up here, please take a look on this case: https://godbolt.org/z/cxqG8qMEK
As you can see, there is no need for custom ser/des for this aggregate:
```
	struct ElementTest
	{
		NodeTest node_;
		CISTA::vector<CISTA::ptr<ElementTest>> paths_;
	};
```

It is that because `serialize(..., const VEC2* element, ...)` is visible to cista:
```
    namespace TEST
    {
        struct VEC2
        {
            float                                   x, y;
            constexpr VEC2()                      : x(0.0f), y(0.0f) { }
            constexpr VEC2(float _x, float _y)    : x(_x), y(_y) { }
        };

        template <typename Context>
        void serialize(Context& context, const VEC2* element, const cista::offset_t)
        {
            context.write(element, (cista::offset_t)sizeof(VEC2));
        }        
    }
```

Whereas moving serialize outside `namespace TEST` makes it not visible and leads to a need of custom ser/des for whole `struct ElementTest`:
```
    using namespace TEST; //dummy
 
    template <typename Context>
    void serialize(Context& context, const TEST::VEC2* element, const cista::offset_t)
    {
        context.write(element, (cista::offset_t)sizeof(TEST::VEC2));
    }
```

**Comment by felixguendling** [comment]
This is not cista specific. It's C++ ADL - you can look up how it works on Google. Basically what the compiler does when looking up functions it considers also the namespace of the function arguments. For this to work, you need to place the serialization functions in the same namespace as the type itself. However, I don't see the problem with this approach. There are alternatives (tag based dispatch for example) but in this case ADL should be fine. It does not justify breaking the cista library interface.

**Comment by ChemistAion** [comment]
Thank you for time and clarification.
