### ISSUE TITLE
Strengthen decay_t utility for std::reference_wrapper<> types

### ISSUE THREAD

**Issue by ChemiaAion** [felixguendling/cista#15]
Hi,

As I mentioned in #13 we should also handle type ref decay for `std::reference_wrapper<>`;

This thing will pass a reference under the radar of `std::remove_reference_t<>`;
Please take a look on my gist for related test snippets: [Type Reference Decay Tryouts](https://gist.github.com/ChemiaAion/05fa1c4477fa0524ac8f93b5ce36d077)

Please improve the `decay_t` utility by `std::reference_wrapper<>` dedicated decay layer, e.g. something like `DecayReferenceWrapper` from my gist.

**Comment by felixguendling** [comment]
I think #16 should do this.

**Comment by ChemiaAion** [comment]
Yes, it does - I think we could close this.

**Comment by felixguendling** [comment]
Ok, thank you for your contribution! 👍
