### ISSUE TITLE
Build fails with the "use of undeclared identifier 'mi_malloc_aligned'" error

### ISSUE THREAD

**Issue by tocic** [felixguendling/cista#154]
1. `mkdir test && cd test`
2. `wget https://github.com/felixguendling/cista/releases/download/v0.10/cista.h`
3. `echo '#include "cista.h"' > main.cpp`
4. `clang++ -std=c++17 main.cpp`

leads to

```
In file included from main.cpp:1:
./cista.h:2949:9: error: use of undeclared identifier 'mi_malloc_aligned'
        CISTA_ALIGNED_ALLOC(ALIGNMENT, static_cast<size_t>(size)));
        ^
```

> clang version 14.0.6
> Target: x86_64-pc-linux-gnu

Seems like [this line](https://github.com/felixguendling/cista/blob/eb1b0199eef401493db0d2dd735a14481b823083/include/cista/aligned_alloc.h#L25) is missing from the amalgamated file.

**Comment by felixguendling** [comment]
Currently, the assumption is that if you have the `mimalloc.h` available as an include, then you want to use mimalloc. Maybe this is not the right way to do it and cista should have a flag `CISTA_WITH_MIMALLOC=1` to indicate that you want to use mimalloc.

**Comment by tocic** [comment]
In my case, the `mimalloc` package is just a dependency of another, unrelated project, [`mold`](https://github.com/rui314/mold), so I definitely didn't want to use `mimalloc` here. I think a more correct assumption would be that if you have already included the `mimalloc.h` header in your project, then you want to use it in `cista`. In this case, you should check for the presence of some predefined macro like `MI_MALLOC_VERSION` instead of the header existance. Your suggestion to explicitly request `mimalloc` works too.

Anyway, the problem at hand is that in the amalgamated file after checking for the existence of the header, we assume that it is already included. I think the easiest solution is to change [the aforementioned line](https://github.com/felixguendling/cista/blob/eb1b0199eef401493db0d2dd735a14481b823083/include/cista/aligned_alloc.h#L25) as follows:

```diff
25c25
< #include "mimalloc.h"
---
> #include <mimalloc.h>
```

Now, `uniter.cc` [ignores](https://github.com/felixguendling/cista/blob/master/tools/uniter/uniter.cc#L17) this line and the amalgamated file will change as follows:

```diff
1978c1978
< // mimalloc.h: basic_ios::clear: iostream error
---
> #include <mimalloc.h>
```

But then you still need to link to the library in order to use its functions.

**Comment by felixguendling** [comment]
I think the `CISTA_WITH_MIMALLOC` gives the use more options to have mimalloc installed but not use it. #159 fixes it. Please reopen / create a new issue if the change causes new issues. Thank you very much for bringing up this issue!

**Comment by tocic** [comment]
Thank you for quick resolution! Do you plan to update the release assets soon or is it better to manually build `cista.h` from the top master's commit?

**Comment by felixguendling** [comment]
Every PR build produces a `cista.h` artifact that can be used if no release is available.

The new v0.11 contains the changes from this PR.
