### ISSUE TITLE
Feature request: specialize exceptions to cista

### ISSUE THREAD

**Issue by AdelKS** [felixguendling/cista#155]
Hello,

Specializing exceptions that cista throws would be very nice to be able to tell them apart from other kinds of exceptions through specialized catch clauses. For example a  `cista::deserialize_error("Invalid type hash")` will enable to not abort the program when simply trying to deserialize.

What do you think ?

Currently there still is the possibility to do this downstream, by `try-catch`ing cista calls and rethrowing specialized exceptions down the stack.

Adel

**Comment by felixguendling** [comment]
This sounds reasonable. Thank you for your proposal!

**Comment by felixguendling** [comment]
https://github.com/felixguendling/cista/pull/158 introduces basic support for catching exceptions coming from cista. Please create a new issue if you require more detailed distinction between exceptions. Thank you for bringing this up!

**Comment by AdelKS** [comment]
Thanks for your great work ! That's already plenty.
