### ISSUE TITLE
nigiri Branch entfernt

### ISSUE THREAD

**Issue by Gendrik24** [felixguendling/cista#167]
Hi, ich arbeite im Rahmen meiner Bachelor Arbeit mit motis/nigiri und musste feststellen, dass der nigiri Branch nicht mehr sichtbar ist. Problem ist, dass der nigiri Branch von motis vom nigiri Branch von cista abhängt und ich nicht einfach den master Branch von cista nehmen kann, da es dort z.B. nicht den matrix container, so wie es ihn in cista/nigiri gab, existiert. Ist der nigiri Branch in Zukunft wieder sichtbar oder im master-Branch wiederzufinden?
VG

**Comment by felixguendling** [comment]
fixed:
- https://github.com/motis-project/nigiri/pull/18
- https://github.com/felixguendling/cista/pull/169
