### ISSUE TITLE
Custom type size calculations are too early during serialization

### ISSUE THREAD

**Issue by ChemiaAion** [felixguendling/cista#17]
Hi!

During serialization, the size of a type provided is calculated by `sizeof(value)`, here:
https://github.com/felixguendling/cista/blob/707ef83b3302104a2aeac5714ff9148ac2e94dc4/include/cista/serialization.h#L194-L196

This is too early IMO to calculate size and alignment when working with custom type.

For example, let's consider these structs:

`struct Simple { std::vector<int> data; } simple;`
`template <typename Ctx>`
`void serialize(Ctx& c, Simple const* el, offset_t const pos) { c.write(pos, el->data[0]); }`

`struct Complex { Simple simple1; Simple simple2; Simple simple3; } complex;`
`template <typename Ctx>`
`void serialize(Ctx& c, Complex const* el, offset_t const pos) { c.write(pos, (int)42); }`

When serialized, they will create 0x20 and 0x60 bytes respectiviely (std::vector<int> from MVSC 2017 15.9.0) for `cista::byte_buf` as a result of sizeof(Simple) and sizeof(Complex) - this cannot be easily overloaded in custom serialization since Context is already given (alocated) and it could only grow.

**Comment by felixguendling** [comment]
We could provide the option to write a custom `sizeof` which defaults to the "real" `sizeof()`. So if you override this for your type, your custom size is used, otherwise it's just `sizeof()`. Alignment would work analogously.

**Comment by ChemiaAion** [comment]
What I want to point out is lack of full control over the output size during custom type serialization.
The std::vector thing is only a dummy to show the case: even custom serialization is implemented we are still geting a full `sizeof(CustomType)` stream.

It would be nice that we could control this, e.g.: to ommit some fields serialization perhaps.

**Comment by ChemiaAion** [comment]
The use case for that whould be, e.g. cache factory for assets:
1.Let's have a lot of templated `<asset>` types with all the possible crazy internals - some asset natives, no cista here;
2. what we need is a serializer for each asset type which returns streamed cista-based containers structure `cache<asset>` with baked/compiled/decompressed/whatever asset data, all not necessary/superflous data will be not transfered to `cache<asset>`;
3. The accessors of `<asset>` will checks if coresponding cache is available - if so, we are working with `<asset>` through deserialized cista-based `cache<asset>`, if not - we have to load/buid asset with it's cache;

**Comment by ChemiaAion** [comment]
I think I could manage my use case without breaking the current API, so we could close this as a "non applicable".

Tanks.

**Comment by felixguendling** [comment]
I think you have a point with this. But there are some limitations.

But I'm not sure how to make something like `CustomContainer1<CustomContainer2<T>>` work recursively: generally, any continuous storage type (like `std::vector<T>` or `cista::vector<T>`) requires the `T`s to be of equal size. This is no longer the case if you have a function `serialized_size<T>(T const& instance)` which may return another size for every instance.

So the only thing I can imagine is a `constexpr` function `serialized_size<T>()` that does not take a specific instance and returns the size required in the buffer. This way, you can store custom structs in a more space-saving way because this allows `sizeof(T) >= serialized_size<T>()`.

Do you think this would be beneficial?

**Comment by felixguendling** [comment]
Making `sizeof` customizable is not sufficient for the vector write:
https://github.com/felixguendling/cista/blob/f18411f7e5e5d2814dcb0594933f75a9e28ca96e/include/cista/serialization.h#L104-L109

Not sure how to solve this. I think, currently, this is inherently against the concept of cista's current design.

**Comment by ChemiaAion** [comment]
Please correct me if I am not seeing all the problems but regarding the vector issue, we have got these `<T>` cases: pointer-like, scalar, aggregate-like (decay_t utility), and last one: everything else - so, we need to provide extra template/constexpr-sizeof for a few _knowns_ `<T>` only.

Let's note the obvious but important thing: this kind of conversion (serializing `Type` to `Other`) is one-way only, you exactly know what you are doing and it is your resposibility to make it right - there is no need for bullet-proof approach from cista point of view.

IMHO all we need to handle these other-type-returned cases are these two things:
1. The `serialized_size<T>()` utility.
2. `cista::array` - to handle to static-size data recursively in fastest way (know size);

**Comment by felixguendling** [comment]
Okay, I think the serialization phase would work this way (replacing `sizeof(T)` by `constexpr serialized_size<T>()`). But I'm not sure about how deserialization should work if `serialized_size<T>()` is smaller than `sizeof(T)`: if you are serializing `Type` to `Other`, there is not enough space to convert `Other` back to `Type` in the serialized buffer / file.

> this kind of conversion (serializing Type to Other) is one-way only

That's a problem on the deserialization side where it needs to be two-way: basically, loading a buffer in cista is just a cast (`cista::offset`) or a cast and recursive pointer conversion from relative offsets to absolute pointers (`cista::raw`). But if you have serialized `Other` and want `Type` back (with `sizeof(Other) < sizeof(Type)`) there is simply not enough space for `Type`. Pretending there is, would result in other problems (invalid reads, etc.).

So for your example:

```cpp
struct Simple { std::vector<int> data; } simple;
template <typename Ctx>
void serialize(Ctx& c, Simple const* el, offset_t const pos) { c.write(pos, el->data[0]); }
```

You cannot call `deserialize<Simple>(buf)` and handle the serialized `el->data[0]` (4-byte) as a full-featured `std::vector<int>` (of size 0x20 for MVSC 2017 15.9.0).

I think implementing `cista::array<T, Size>` can be done independently of the `serialized_size<T>()` feature.

**Comment by ChemiaAion** [comment]
This is exacly what I want to say, first, whenever the `Type` does not pass aggregate/layout/polymorphic assert you have to provide a custom serializer to work with cista.
Second, `constexpr serialized_size<T>()` utility will allow to do everything during serialization.

Now, I think that desierializer will work perfectly fine as-is if there always will be a deserializer provided.
So it would be best if this custom `Type` serializer requirement would be extended also for `Type` deserializer: as you point out - we should not assume default casting-like deserialization for `Type` **whenever custom** serializer for `Type` is provided.

Going this way, it will be up to the `Type` to handle all the de-/serialization conversions.
Like in my examle above: when I "compress" whole std::vector to one value, it is up to me now: how to rebuild it back from that one value during deserialization.

**Comment by felixguendling** [comment]
> how to rebuild it back from that one value during deserialization

That's the question I'm asking me here: there is no way to get back a full `std::vector<T>` because there is not even enough space for its member fields. If you would pack/compress `el->data[0]` to the place where the vector will later be and leave enough space for the vector, then it could work.

Could you please provide an example deserialization function? For example in form of a test case.

PR #19 implements `cista::array<T, Size>` and `seriailzed_size<T>` which defaults to `sizeof(decay_t<T>)`.

**Comment by felixguendling** [comment]
Strangly, the MSVC debug build has some issues with the `serialized_size<T>()` utility I can't explain:
https://ci.appveyor.com/project/felixguendling/cista/builds/23320704

So I've removed this feature from the PR for now. The `cista::array<T, Size>` type is working. It's a thin wrapper around the basic C array.

**Comment by ChemiaAion** [comment]
Could you please leave this PR for an hour or so...

**Comment by felixguendling** [comment]
Yes, I will leave it open until you've reviewed it.
It's always better to have more eyes on the code.

> I will try to track it down

Thank you!
I've tried to track it down too but with no success. It's simply `serialized_size<T>()` returns another value than simply calling `sizeof(T)` directly. Every other build (MSVC Release and Clang/GCC on Linux/TravisCI and Mac OS X/my other dev machine)

**Comment by ChemiaAion** [comment]
FYI: changing `constexpr serialized_size<T>()` to `static/static inline` makes tests happy.
Seems that non-static inline-ing (default or forced) provides bad result, perhaps context in which serialized_size is inlined is somehow important? I do not know.

Compile with: Microsoft Visual Studio Community 2017 Version 15.9.9 (VisualStudio.15.Release/15.9.9+28307.518)

**Comment by felixguendling** [comment]
Thank you! 👍
PR #19 is merged now.

**Comment by ChemiaAion** [comment]
I am happy that I could help :)

Right now I am heavily testing my `CustomType` de-/serializer example, and for now I have noticed that context (i.e.: `cista::byte_buf` etc.) does not respect `serialized_size`, e.g.: for direct cista::serialize `CustomType` we are still gettin context as as it was for `sizeof(CustomType)`.

This is not a blocker for me, but we should take a look on that...
I will finish the example first and then let's discuss the eventual issues - if any.

Best regards,
RTJ

**Comment by felixguendling** [comment]
Yes, I missed that. Should be fixed in PR #20.
The example would be really interesting as a test case for CI. And I have still no clue how deserialization could work when there's not enough memory space for the vector's member variables. I'll leave it open for now.

**Comment by ChemiaAion** [comment]
Here is my playground: [CustomType tests](https://gist.github.com/ChemiaAion/7d7a9b1a64e54def061acb48e498f985)

As we spoke, serialization works out-of-the box, even for cista::vector embedded `CustomType`.

Deserialization is a little bit more hack-y...
We could build non-serialized internals based on simple metadata, this is pretty straightforward.
Then, I am just replacing the pointer returned by `T* unchecked_deserialize(uint8_t* from, uint8_t* to = nullptr)`.
The missing thing here is that I cannot pass back anything up to `T* unchecked_deserialize(...)` through lower `unchecked_deserialize(ctx&, (...)*)` specializations - to solve that I add some extra custom explicit instantiation for my `CustomType`.
I think, this can be somehow easily solved if all `xxx_deserialize(ctx&, (...)*)` specializations will use `(...)**` istead.

I have tried also `cista::vector<CustomType>` and I could rebuild its elements one by one.
Now, it would be possible to recreate cista::vector<CustomType> from these elements and pass it up to `T* unchecked_deserialize(...)` but without of `xxx_deserialize(ctx&, types**)` specialization it would be too many custom explicit instantiation to do.

Let's summarize:
1. Latest PRs (#18, #19, #20) allows fine control of de-/serialization;
2. Please consider  `xxx_deserialize(ctx&, (...)**)` specializations to allow return the result for simpler customization;
3. Issue: cista containers inc/dec operators (iterators related) are missing - default ones are using sizeof(Type) instead of serialized_size<Type>;

**Comment by felixguendling** [comment]
I have a querstion regarding deserialization:

In L88 you assign the newly allocated pointer of the first element (`custom_struct*`) to `cista::vector<custom_struct>::el_` [0]. But the other values created in L96 are not used. So they don't end up in the vector. I would assume that this is not how it is intended to work? How would this look like if you had `deserialize<T>(ctx&, T**)` interfaces?

In both use cases in your gist the custom data structure was behind a pointer (either `vector::el_` or the return value of `deserialize`). But as soon as you have a custom data structure as a member variable of a struct, you need to have custom deserializers that do "dirty tricks" for all types up the chain until you can hide behind a pointer that allows you to allocate more memory than there is actually available in the serialized buffer.

Another issue is memory management: now you have some pointers here and there in the deserialized buffer that will simply leak memory even if you deallocate the buffer itself. There is no mechanism to clean them up. Usually, `cista` data structures know whether they should release the memory or not (`self_allocated_` flag) which allows the modification (including resize) of deserialized data structures. Of course we can say "you do custom stuff - you need to care for your memory yourself". But wouldn't it be nice to have a generic/carefree/foolproof solution to this, too?

**Comment by ChemiaAion** [comment]
There is no memory management in this example and you are absolutely right that we should stay-with/recommend the cista-generic approach, point.

You are right with all the questioned cases, point again.
I apologize for not addressing them all, I would like to humble switch to my point of view instead.
**My goal during this particular discussion (#17) is what I proposing during some (maybe a little bit edge-cases) research: with no-cost cista API changes you would be able to do all the fancy/magic things - if you want - if so, then it is your story how you handle/manage them - cista itself is generic.**

Such as my proposal (2) for example, this will allow you to do all the magic, whenever you needs it - with no overhead for generic use.
Look like all these proposed deserializer `deserialize<T>(ctx&, T**)` specifications `for_each_ptr_field` invocation (I've counted three of them) would be a little bit funny but does the job, i.e.:
`for_each_ptr_field(*(*spec_type), [&](auto& field) { deserialize(context, &field); });`

IMHO this way the whole THING is super bullet-proof for generic use, no one will ever notice the possibilities, but whenever you are doing some customization you are able to do absolutely everything.

**Comment by ChemiaAion** [comment]
For the note: current approach (#18, #19, #20) is absolutely enough to close this isses as-is.

**Comment by felixguendling** [comment]
Okay, I'm closing this. Thank you for your support 👍 

I'm not sure how to implement your proposed change because a pointer to a pointer makes only sense if you have a pointer to point to in the first place. That's not the case for value types (such as member variables or array entries). So I'll leave this to someone who requires it and provides a PR.

But as your example shows, it is possible to do magic everywhere you have a pointer to modify - i.e. at the root deserialize function or at `cista::unqiue_ptr<T>` / `cista::vector<T>`. I think that is sufficient for now.

**Comment by ChemiaAion** [comment]
I want to also thank you for the very informative discussions here all around.
