### ISSUE TITLE
Create a stable release branch

### ISSUE THREAD

**Issue by g-arjones** [felixguendling/cista#184]
I'm currently using cista in a larger project (we use dozens of proprietary and 3rd-party repositories to build our workspace) and the fact cista does not provide a stable release branch is becoming a nuisance for us because it causes constant and unnecessary rebuilds given how frequently new commits are added to the master/devel branch.

Would you consider creating a stable branch that would only be updated when a new version was released? I would really appreciate that.

Thanks!

**Comment by felixguendling** [comment]
Sure, that's possible. To understand your issue better: would it be an option to use the latest release tag?
All releases are tagged - a tag is (just like a branch) usable as a Git reference: https://github.com/felixguendling/cista/tree/v0.13
In the projects where we use cista, we just reference an exact Git hash (but a tag would also work), so each project can update its dependencies at its own pace: https://github.com/motis-project/motis/blob/master/.pkg#L8

But of course, it's also possible to add a 'dev' branch and only merge to the 'master' branch for releases.

**Comment by felixguendling** [comment]
In general I would not recommend referencing just a branch head for a dependency because even with the solution to have a separate release branch, there can be breaking changes that you don't want to have in your build immediately. You want to make a strategic decision when to upgrade to which release (depending on: do you benefit from the new features that were added, are the bug fixes relevant for your project? etc.).

**Comment by g-arjones** [comment]
> In general I would not recommend referencing just a branch head for a dependency because even with the solution to have a separate release branch

We have internal tooling that takes care of that. During development, we use branch heads but as we prepare for a release we pin all 3rd-party projects we use and then generate our own stable branches with them.

So, a stable branch really fits our use case better than just commit tags.

**Comment by felixguendling** [comment]
I created a stable branch. Will rebase the `stable` on `master` for each new release tag.
https://github.com/felixguendling/cista/tree/stable

**Comment by g-arjones** [comment]
Thanks a lot!
