### ISSUE TITLE
Extension proposal for serialized_size()

### ISSUE THREAD

**Issue by ChemiaAion** [felixguendling/cista#22]
Hi,

Could you please consider making the `constexpr serialized_size()` as a pure non-constexpr inlined static func with default `void* = nullptr` argument?
This will add much more more flexibility IMHO for advanced customizations, with relatively (if any) low cost from cista point of view, AFIK this should/would be pretty simple inlined...

That is to say, it will allow to `auto custom = reinterpret_cast<CustomType*>(proposed_void_arg);` and then some direct fancy `CustomType` size calculations.

**Comment by felixguendling** [comment]
Like in #23?

https://github.com/felixguendling/cista/blob/e58fe887465b5663be7519b786415ac9b025e898/include/cista/serialized_size.h#L9-L13

**Comment by ChemiaAion** [comment]
Perfect!
