### ISSUE TITLE
unique_ptr does not support polymorphic conversions (derived to base)

### ISSUE THREAD

**Issue by opera-aberglund** [felixguendling/cista#231]
Currently, cista::(offset/raw)::unique_ptr does not support automatic polymorphic conversions when assigning a unique_ptr to a base class from a derived class. This forces users to manually release the raw pointer from the derived class and explicitly cast it to the base class. In contrast, std::unique_ptr handles this conversion automatically, making it more convenient and safer to use in polymorphic contexts.

Example:

```c++
#include <iostream>
#include "cista/cista.hpp"

// Base class
struct Base {
    virtual ~Base() = default;
    virtual void say_hello() const { std::cout << "Hello from Base\n"; }
};

// Derived class
struct Derived : Base {
    void say_hello() const override { std::cout << "Hello from Derived\n"; }
};

int main() {
    // Using std::unique_ptr
    std::unique_ptr<Base> std_base_ptr = std::make_unique<Derived>(); // Works automatically
    std_base_ptr->say_hello();

    // Using cista::offset::unique_ptr
    cista::offset::unique_ptr<Base> cista_base_ptr = cista::offset::make_unique<Derived>(); // Fails, no viable constructor.
    cista_base_ptr->say_hello();

    return 0;
}
```

**Comment by felixguendling** [comment]
In this case, serialization would not be safe because the class contains a virtual function table. I'm not sure if adding this functionality would lead to the impression that such a owning pointer could be serialized + deserialized?

**Comment by opera-aberglund** [comment]
I see, so there is really no way to automatically serialize a virtual class? I just ran into this problem now and I suppose the only solution would be to just use a custom serializer for this type?

**Comment by felixguendling** [comment]
When designing as system I don't use virtual functions for parts that should be serializable. There are options such as `variant` that also usually have better runtime performance. Or storing the type manually (e.g. in a separate vector to get writ of padding bytes) and use a union (also requires a custom de/serialization function).

I never tried to serialize a class with a virtual function table. Maybe it even works in some cases. But I would not expect it to work.

**Comment by opera-aberglund** [comment]
Good point. I'm working on rewriting a physics engine [(this one)](https://github.com/louis-langholtz/PlayRho) to support serialization, so I basically just replace everything with Cista structs. It uses a pointer-to-implementation design, so everything is contained in a unique_ptr to a virtual class, but now I'm thinking of just rewriting this part too to remove the virtual class and just point directly to the derived class.

**Comment by felixguendling** [comment]
Yes, inheritance on its own should work with serialization. So you could also replace virtual functions with global functions (static functions / friend functions / free functions). As long as they can figure out what to cast to, it should work.
