### ISSUE TITLE
[Question] How to (de-)serialize multiple types with a single buffer correctly?

### ISSUE THREAD

**Issue by maichmueller** [felixguendling/cista#240]
Hi, 

I am trying to use your library to support python pickling for pybind11 exposed types. This requires serialization of non-aggregate types with fields of primitive (double, int, etc) and dynamic types (e.g. std::vectors/map/unordered_map etc.). 
My idea was to serialize all the data into a single `cista::buf` object upon pickling and readout the different types in the correct order upon unpickling. 

I haven't got much experience with serialization and alignment, but with a little google-fu I pieced this read-function together to fetch data at a specific offset which I update with every read:
```c++
template<typename T>
inline T* read(cista::buf<>& buffer, long& offset)
{
    offset = (offset + alignof(T) - 1) & ~(alignof(T) - 1);

    T* ptr = cista::deserialize<T, cista::mode::CAST>(buffer.addr(offset));

    offset += sizeof(T);
    return ptr;
}
```
and this method works well for non-nested data and even cista::strings it seems, but fails with e.g. std::vector (or cista::vector):

```c++
struct A
{
    char a;
    char b;

    bool operator==(const A& other) const { return a == other.a && b == other.b; }
};

cista::buf buffer {};
auto values = std::tuple {
    A { 'a', 'b' },  
    'c',
    A { 'x', 'y' },  
    'd',
    std::pow(2, 30),
    636,
//    std:vector<char> { 'w', 'h', 'a', 't', '?' },  // this will not work (no serializer)
//    data::vector<char> { 'w', 'h', 'a', 't', '?' },   // this will not work (wrong serialization)
    cista::basic_string<const char*> { "Hello, World!" },
    3.14,
};
// Serialize the values
std::apply([&](auto&&... args) { (cista::serialize(buffer, args), ...); }, values);
// Deserialize the values
std::apply(
    [&, offset = 0l]<typename... Ts>(Ts&&... args) mutable
    {
        (std::invoke(
             [&]<typename T>(const T& expected)
             {
                 auto* read_value = read<T>(buffer, offset);
                 fmt::println("Expected: {}, Read: {}", expected, *read_value);
             },
             std::forward<Ts>(args)),
         ...);
    },
    values);
```

To serialize std::vector I then borrowed from [your tests](https://github.com/felixguendling/cista/blob/master/test/std_vector_test.cc).
Using this serialization with the above `read`-function will spew out wrong values when adding cista::offset::vector to the tuple and cause a segfault with std::vector added in.

I suppose my `read` function is just wrong, but I don't see how to do it right. Are there cista utilities i can use for this I haven't seen yet?

Side-question: Why does your std::vector serialization method work for...

- `std::vector< T >`

- `cista::offset::vector< std::vector< T > >`

- `std::vector< cista::offset::vector< std::vector< T > > >`

but not for e.g `std::vector< std::vector< T > >`? What would I need to change to make it compatible with nested std:: vectors?

**Comment by felixguendling** [comment]
I'm not sure if I understand the problem correctly. The main idea of cista is that you use cista data structures for everything you want to serialize. So instead of `std::vector`, `cista::raw::vector` or `cista::offset::vector` would make everything very easy.

If you want to serialize multiple data structures into a buffer, then `cista::tuple` should do the job.

Conceptually, there's no data structure you mentioned that's not already supported by cista.

**Comment by felixguendling** [comment]
Maybe you can provide a minimal test case with something that should work in your opinion but doesn't?

**Comment by felixguendling** [comment]
As a hashmap we only use this:
https://github.com/motis-project/unordered_dense/blob/main/include/ankerl/cista_adapter.h

In general your use case doesn't look very suited for cista.
Have you looked into zpp_bits? According to the benchmarks it provides similar performance to cista but it would probably be more compatible to your approach (as you're force to serialize third-party data structures which is not compatible to cista's zero-copy benefits):
https://github.com/eyalz800/zpp_bits

**Comment by maichmueller** [comment]
ah interesting, that is exactly the hashmap in need. Nice that you have an adapter for it! 

Cista is already largely integrated in our codebase, just not in the exact way of using cista drop-in replacements, but rather 'on-demand'. I do in fact have access to the data structures in my code, it is just a large refactoring to make it fully cista-based (this scenario was meant as a general example as well). Either way, shouldn't I expect such an example as above with std::vector to serialize correctly as well (given that the serialization method is correct)?

I will try to refactor the relevant `std` components with`cista` equivalents and report back if something goes awry!

**Comment by felixguendling** [comment]
- you can't use `CAST` mode unless you're 100% sure you can (only offset pointers or no pointers at all, no endian conversion and no checks required)
- the code only worked because the original struct was still alive (so effectively nothing worked)
- tuple deserialization had a bug (should be fixed now on master)

We don't use cista everywhere. Just in case something has to be serialized.

**Comment by felixguendling** [comment]
Don't forget to call the destructor manually for vector deserialization (another problem with not using cista structs).

I hope this is fixed now with
- f2df3af690f2d93e61644008ea07f47d319381c2
- 177747960ab7def5f1123a2790a3a3ff62a303e5

Closing. Reopen in case it's still not working.
