### ISSUE TITLE
cista::variant<>

### ISSUE THREAD

**Issue by cflaviu** [felixguendling/cista#35]
Hi, the library looks great but it seems there is no support for unions. Unions are needed for polymorphism. 

I tried
```
	struct my_struct {  // Define your struct.
		int a_{0};
		union inner {
			int b_{0};
			char d_;
		} j;
	};
```
and the main error using VS2019 is C2672:  'arity': no matching overloaded function found
and using latest GCC is cista.h:1290:31: error: no matching function for call to ‘arity(const main()::my_struct::inner&)’.

Maybe std::variant would help in this case instead of plain union.

**Comment by felixguendling** [comment]
**Answer for the current state:**

Since the reflection mechanism uses structured bindings (`auto [x]  = j;` in your case) and this cannot work with instances of union data structures, there is no easy way to make it work automatically. You can, however, write a custom serialization function and deserialization function as described in the documentation.

For your case (since all union members are scalar values) it is sufficient to have a simple/empty custom serialize/deserialize function:

```cpp
#include <cassert>
#include "cista.h"

struct my_struct {  // Define your struct.
  int a_{0};
  union inner {
    int b_{0};
    char d_;
  } j;
};

template <typename Ctx>
void serialize(Ctx&, my_struct const*, cista::offset_t const) {}

void deserialize(cista::deserialization_context const&, my_struct*) {}

int main() {
    namespace data = cista::offset;
    
    std::vector<unsigned char> buf;
    {  // Serialize an object of class my_struct.
      my_struct obj;
      obj.a_ = 7;
      obj.j.d_ = 'c';
      buf = cista::serialize(obj);
    }  // End of life for the "obj" value
    
    // Deserialize and read.
    auto deserialized = data::deserialize<my_struct>(buf);
    assert(deserialized->j.d_ == 'c');
}
```

Online example: https://onlinegdb.com/SJa7kmtTN

If you have complex types (e.g. a `cista::vector<T>`) in your union, that require special serialization/deserialization, you need to do this in those custom serialize/deserialize functions:

```cpp
#include <cassert>
#include "cista.h"

namespace data = cista::offset;

struct my_struct {  // Define your struct.
  enum class state : uint8_t { VECTOR, UNIQUE_PTR } a_{state::VECTOR};
  union inner {
    inner() { b_ = data::vector<int>{}; }
    ~inner() { /* leaks, requires access to state to call the destructor */ }
    data::vector<int> b_;
    data::unique_ptr<int> c_;
  } j;
};

template <typename Ctx>
void serialize(Ctx& c, my_struct const* origin, cista::offset_t const pos) {
  switch (origin->a_) {
    case my_struct::state::VECTOR:
      cista::serialize(c, &origin->j.b_, pos + offsetof(my_struct, j));
      break;
    case my_struct::state::UNIQUE_PTR:
      cista::serialize(c, &origin->j.c_, pos + offsetof(my_struct, j));
      break;
    default: throw std::runtime_error("invalid struct state");
  }
}

void deserialize(cista::deserialization_context const& c, my_struct* s) {
  switch (s->a_) {
    case my_struct::state::VECTOR: data::deserialize(c, &s->j.b_); break;
    case my_struct::state::UNIQUE_PTR: data::deserialize(c, &s->j.c_); break;
    default: throw std::runtime_error("invalid struct state");
  }
}

int main() {
    std::vector<unsigned char> buf;
    {  // Serialize an object of class my_struct.
      my_struct obj;
      obj.a_ = my_struct::state::UNIQUE_PTR;
      obj.j.c_ = data::make_unique<int>(55);
      buf = cista::serialize(obj);
    }  // End of life for the "obj" value
    
    // Deserialize and read.
    auto deserialized = data::deserialize<my_struct>(buf);
    assert(*deserialized->j.c_ == 55);
}
```

Online example: https://onlinegdb.com/By4cmQt6V

**Maybe future work:**

Since the memory layout of `std::variant` is not specified, it maybe is required to introduce `cista::variant` to have a serializable modern C++ union.

**Comment by felixguendling** [comment]
I'll leave this issue open as a feature request for `cista::variant`.

But as described in my previous post, it is already possible to serialize union data structures using custom serialization/deserialization functions.

**Comment by cflaviu** [comment]
Thanks for explanations.
I have experience using Protobuffers and Flatbuffers and I'm wondering how much C++ meta-programming and reflection could cover the features of code generators based on schemes. I like very much simplicity defining the serialization/de-serialization process, raw performance and memory consumption level of this library.

For the case of unions containing scalars, would be possible to enable those two empty functions if all members of the union are scalars by statically iterating them and check each one using std::is_scalar?

**Comment by felixguendling** [comment]
I have extended the current version (`master` branch, but not released yet!):
https://github.com/felixguendling/cista/commit/dac7590689635b58bbceb385a00f80c55cac4e90

Now, you  don't need to write separate de(serialization) functions for simple union struct that are trivially copyable.

Note that the deserialize function signature changed if you want to switch to the new version. I will document all changes and the new functionality with the new (major) release.

**Comment by felixguendling** [comment]
But a `cista::variant` which supports non-trivial union data structures, too, would be a sensible extension to the library.
