### ISSUE TITLE
Next release ?

### ISSUE THREAD

**Issue by mrogez-yseop** [felixguendling/cista#41]
The last release (0.4) dates back from 2 Jan 2019 and many useful commits have happened since.
Do you have a rough estimate of when you might make a new release ?
And maybe what do you think is missing that you want for the next release to happen ?

Thanks for this very nice serialization library.

**Comment by felixguendling** [comment]
[0.5 is out](https://github.com/felixguendling/cista/releases/tag/v0.5)
