### ISSUE TITLE
How to build release from branch master

### ISSUE THREAD

**Issue by westfly** [felixguendling/cista#46]
Hi
the current release of  version is 0.4, which is behand master too much
I'm trying to build release from master branch
```shell
mkdir build;
cd build
cmake3 -f CMakeLists.txt -DCMAKE_CXX_COMPILER=/opt/scylladb/bin/g++ ../
make
```
configure is ok,but nothing can be found at dir build or subdir

**Comment by felixguendling** [comment]
The `cista.h` single-header file will be generated with the `make cista-test-single-header` target.

For larger projects, I would recommend using Cista as a CMake library:

```CMake
    add_subdirectory(cista)
    # ...
    target_link_libraries(my_target cista)
```

And in your project source code:
```cpp
#include "cista/containers/vector.h"
#include "cista/reflection/to_tuple.h"
// ...
```

This way, you can include only the headers you need which could improve compilation times.

**Comment by westfly** [comment]
OK,thanks for your replying. I'll try both method.
