### ISSUE TITLE
std::aligned_alloc  is not a member of std

### ISSUE THREAD

**Issue by westfly** [felixguendling/cista#49]
I'm using devtoolset-8 on centos7 to get a higher verison of gcc without influencing the system gcc。
when compiler the master, I get on error as blew
thirdparty/cista/aligned_alloc.h:28:9: error: ‘aligned_alloc’ is not a member of ‘std’
   (std::aligned_alloc(  

The reason is that libc is to old from the answer [compiler-cant-find-aligned-alloc-function]( https://stackoverflow.com/questions/52777209/compiler-cant-find-aligned-alloc-function) 
```c
#if __cplusplus >= 201703L && defined(_GLIBCXX_HAVE_ALIGNED_ALLOC)
  using ::aligned_alloc;
#endif
```
so I change to code to fix this error
```diff
+#elif defined(_GLIBCXX_HAVE_ALIGNED_ALLOC)
+    #include <memory>
+    #define CISTA_ALIGNED_ALLOC(alignment, size) \
+        (std::aligned_alloc(                       \
+            cista::next_power_of_two((alignment)), \
+            cista::to_next_multiple((size), cista::next_power_of_two((alignment)))))
 #else
-#include <memory>
-#define CISTA_ALIGNED_ALLOC(alignment, size) \
-  (std::aligned_alloc(                       \
-      cista::next_power_of_two((alignment)), \
-      cista::to_next_multiple((size), cista::next_power_of_two((alignment)))))
+    #define CISTA_ALIGNED_ALLOC(alignment, size) (std::malloc((size)))
 #define CISTA_ALIGNED_FREE(ptr) std::free((ptr))
```

**Comment by felixguendling** [comment]
Thank you very much for the feedback!

Can you please try the new version:
https://github.com/felixguendling/cista/blob/945a609dd3df0f3340e5f07fc2ccc33dfe8afde3/include/cista/aligned_alloc.h#L21-L32

I tried to find a solution that works for libstdc++ as well as libc++.

**Comment by westfly** [comment]
Thx, It's works.
