### ISSUE TITLE
 structured bindings failed when processing struct has base type

### ISSUE THREAD

**Issue by ivytin** [felixguendling/cista#53]
Guys  I got some trouble when serialize a struct has base, I simplified  code into following
```cpp
struct Base {};
struct Derive:Base {
  int field;
};

// ......
// Derive d = {{}, 0};
std::vector<uint8_t> out = cista::serialize<MODE, Derive>(d);
};
```

And the compiler gave error like 
```bash
/**/cista-0.6/include/cista/reflection/to_tuple.h:230:11: error: type 'const Derive' decomposes into 1 elements, but 2 names were provided
    auto& [p1, p2] = t;
          ^
```

Obviously, the prolblem was caused because `Derive d` has to be init like `{{}, 0}` rather than `{0}`, so the `arity()` gives the number of binging arguments is 2.

So, is there any way to solve it or we just can not use cista to serialize struct with inheritance?

**Comment by felixguendling** [comment]
Yes, as documented, the "automatic" mode only works for standard layout, non-polymorphic aggregate types.

But you can do this with a custom (de)serialization function:
https://github.com/felixguendling/cista/blob/494d1add411c858ebac0ce5f492e11df4c595918/test/union_derive_test.cc#L31-L53

Often, you use inheritance to have some kind of polymorphism. This can be accomplished like in this example:
https://github.com/felixguendling/cista/blob/494d1add411c858ebac0ce5f492e11df4c595918/test/union_derive_test.cc#L55-L128

This would be much more concise if Cista would provide a `cista::variant`.

**Comment by ivytin** [comment]
Thank u, i solved my problem by **a custom (de)serialization function** u  mentioned. 👏

However, accroding to the cppreference,  `Derive` is did a standard layout, non-polymorphic aggregate type, that could be proven by
```
std::cout << std::is_standard_layout_v<Derive> << '\n';    // 1
std::cout << std::is_polymorphic_v<Derive> << '\n';           // 0
std::cout << std::is_aggregate_v<Derive> << '\n';                 // 1
```
So maybe the inheritance limitation should be added into the doc?

**Comment by felixguendling** [comment]
You are right. I will update the docs and the `static_assert` accordingly.

Thank you!
