### ISSUE TITLE
MSVC Win32 Support

### ISSUE THREAD

**Issue by linuxaged** [felixguendling/cista#55]
i'm trying build against MSVC Win32. Does this assertion means only 64bit is supported?

**Comment by felixguendling** [comment]
Currently, only 32bit big endian on Linux is tested in the CI.
I adjusted the code so that the tests compile on MSVC Win32 on the 'msvc32' branch.
This will be merged when I setup the CI for MSVC 32bit.

**Comment by linuxaged** [comment]
can i get a copy of `cista.h` in the msvc32 branch for testing? how to generate?

**Comment by felixguendling** [comment]
Here: [cista.txt](https://github.com/felixguendling/cista/files/4007033/cista.txt)
To generate it, you have to build the "cista-test-single-header" CMake target (download the project, create build folder, run 'cmake ..' in it). It is located in your build folder.

**Comment by linuxaged** [comment]
thanks!

**Comment by felixguendling** [comment]
now on master
