### ISSUE TITLE
crash at `verify(bool const condition, char const* msg)` when serializing custom type

### ISSUE THREAD

**Issue by linuxaged** [felixguendling/cista#56]
Have not found any example about how to write a custom serialize funtion, so i try myself.
Here is my struct:
```
struct vec3 {
	float x, y, z;
};

struct mat4 {
	float d[16];
};

struct Vertex {
	vec3 position;
	vec3 normal;
};

struct Mesh {
	cista::raw::vector<mat4> transforms;
	cista::raw::vector<Vertex> vertices;
};

using Meshes = cista::raw::vector<Mesh>;
```
And my serialize funtions:
```
template <typename Ctx>
void serialize(Ctx& c, Mesh const* mesh, cista::offset_t const pos) {
	for(auto const& t : mesh->transforms) {
		c.write(pos, t);
	}
	for(auto const& v : mesh->vertices) {
		c.write(pos, v);
	}
}

template <typename Ctx>
void serialize(Ctx& c, Meshes const* meshes, cista::offset_t const pos) {
	for(auto const& mesh : *meshes) {
		c.write(pos, mesh);
	}
}
```
The crash error:

    Unhandled exception at 0x772E35D2 in cista-example.exe: Microsoft C++ exception: std::runtime_error at memory location 0x00BEFAB8.

**Comment by felixguendling** [comment]
Ideally, you also copy&paste the stacktrace.

But from your example code, I would guess that you only have to write a custom serialization/deserialization function for `mat4`. All other data structures either have already a custom (de-)serialization function provided by cista itself (i.e. `cista::raw::vector<T>`) or do not need a custom (de-)serialization function (i.e. `Mesh`). So adding an empty (de)serialization function for `mat4` should be sufficient to serialize meshes in your example.
