### ISSUE TITLE
How could be deserialization in C# for the serialized Data

### ISSUE THREAD

**Issue by sgf** [felixguendling/cista#6]
if im defined the similar data structures in C#;
How could be do deserialize in C# for the Data serialized  by C++.

**Comment by felixguendling** [comment]
Currently, there are no code generators for other languages.
It would be interesting to generate code for other languages (C#, Python, etc.) to access serialized data. My approach would be to parse the C++ data structure definitions (e.g. with foonathan's [cppast](https://github.com/foonathan/cppast)) and then generate wrapper accessors in C# (in your case).
Currently, I don't have enough spare time to experiment with this and I currently don't have a real use case. But feel free to start experimenting with it! :)

**Comment by sgf** [comment]
thank you.

**Comment by qiuwei** [comment]
For python it seems to be easier, we could use pybind to create a binding for the desrielized struct.
