### ISSUE TITLE
`deserialize` doesn't work with `const char*` in non-CAST mode

### ISSUE THREAD

**Issue by dm3** [felixguendling/cista#62]
`deserialize(CharT *in, CharT *out)` only works with `const char*` in CAST mode. If I try setting the mode to non-CAST, `deserialization_context` requires the input to be `char*` and `check` only works with `uint8_t`. 

Is it possible to make the API work with both `const char*` and `const uint8_t*` in all modes?

**Comment by felixguendling** [comment]
Should work now with https://github.com/felixguendling/cista/commit/bbed6aa323a44ed5e5dfc85cc89d7640a3f4ab8a.

**Comment by dm3** [comment]
Now only works with non-const inputs. I'd think `const (unsigned) char*` should also be accepted.

What do you think?

**Comment by felixguendling** [comment]
That is correct. Sorry to close too early. Should work now with https://github.com/felixguendling/cista/commit/35299d69961deff47b15d387e5b2a6e081f1dcc4


> I'd think const (unsigned) char* should also be accepted.

You're right. But watch out that there are requirements: deserialization of raw pointers (e.g. in most `cista::raw` data structures except `cista::array`) as well as endian conversion requires modification of the buffer. If you use offset mode and the deserialization does not require endian conversion, raw inputs can be deserialized: they don't need to be modified.

**Comment by dm3** [comment]
Great! Will keep that in mind. I guess this is also mentioned in the docs, isn't it?

**Comment by felixguendling** [comment]
Yes, it's mentioned but I added an explicit section to the deserialization reference: https://github.com/felixguendling/cista/wiki/Serialization-Reference
