### ISSUE TITLE
CISTA_PRINTABLE doesn't work for enums

### ISSUE THREAD

**Issue by dm3** [felixguendling/cista#64]
Not sure if this can be solved generically, but would be nice if `CISTA_PRINTABLE` worked for e.g. `offset::vector<MyEnum>` by defaulting to the underlying enum type.

**Comment by felixguendling** [comment]
It should work now:

https://github.com/felixguendling/cista/blob/7f41e99a4bbd09e2508bdad4c67f33e88da27a46/include/cista/reflection/printable.h#L12-L50
