### ISSUE TITLE
data::vector cannot be copied

### ISSUE THREAD

**Issue by wphilips** [felixguendling/cista#7]
The following code fails:
namespace data = cista::offset;
data::vector<uint32_t> a;
data::vector<uint32_t> b;
b =a;

Error:
cannot increment value of type 'cista::offset_ptr<unsigned int>'
    for (; copy_source != end_it; ++copy_source, ++copy_target) {

One reason is that operator++ are not defined for offset pointers.

**Comment by felixguendling** [comment]
Hi, thank you for your feedback. I have added the operators and a test case here:
https://github.com/felixguendling/cista/blob/offset_ptr_operators/test/vector_copy_test.cc

(Branch "offset_ptr_operators")
