### ISSUE TITLE
GCC 9.2 - `vector::to_vec` linkage error

### ISSUE THREAD

**Issue by dm3** [felixguendling/cista#71]
Not sure what's exactly causing the issue, but once I nest templates deep enough the following happens upon trying to call the `cista::offset::to_vec(std::vector<double>)` macro:

```
my.cpp: In function `cista::basic_vector<double, cista::offset_ptr<double, void>, false, unsigned int>::basic_vector()':
/usr/local/cista/include/cista/containers/vector.h:21: undefined reference to `cista::offset_ptr<double, void>::offset_ptr(decltype(nullptr))'
my.cpp: In function `cista::basic_vector<double, cista::offset_ptr<double, void>, false, unsigned int>::basic_vector(cista::basic_vector<double, cista::offset_ptr<double, void>, false, unsigned int> const&)':
/usr/local/cista/include/cista/containers/vector.h:47: undefined reference to `cista::offset_ptr<double, void>::offset_ptr(decltype(nullptr))'
collect2: error: ld returned 1 exit status
```

Error disappears once I create and call `to_vec` function instead of the `to_vec` macro:
```
inline auto to_vec(const std::vector<double> &vs) {
  message::data::vector<double> v;
  v.reserve(std::size(vs));
  std::copy(std::cbegin(vs), std::cend(vs), std::back_inserter(v));
  return v;
}
```

If I make the above function a template, i.e. `to_vec<double>(std::vector)`, the link error comes back.

**Comment by felixguendling** [comment]
Can you please post a full code snippet (with includes, main function, etc.) as a minimal example to reproduce?

**Comment by dm3** [comment]
Unfortunately the full example is huge. I don't have the time to extract the minimal failing case.

**Comment by felixguendling** [comment]
Without being able to reproduce the problem, I don't see a chance to fix it. Sorry.

**Comment by dm3** [comment]
Sure. I guess even a closed issue can serve as a reference for other people to contribute if anyone runs into the same issue.

**Comment by felixguendling** [comment]
Ok, I'll leave it open so it will be easier to find.

To anyone out there running into this issue with a smaller example: please post it here so I can fix it.

We're using `to_vec` in [MOTIS](https://github.com/motis-project/motis) all over the place and it's working fine. So it seems to be a special case that's causing the problem.

**Comment by felixguendling** [comment]
Doesn't seem to happen anymore. If it happens, please post here or create a new issue.
