### ISSUE TITLE
how to use std::string?

### ISSUE THREAD

**Issue by dotkt** [felixguendling/cista#85]
![图片](https://user-images.githubusercontent.com/49758966/100592501-24941d00-3332-11eb-8bec-691183eac887.png)

i add std::string member c at the sample code but get this error:
cista.h(4608,19): error C2338: Please implement custom serializer

is there example using std library with cista?

**Comment by felixguendling** [comment]
I would not recommend using `std::` data structures. If you are using only `std::` data structures you can probably also use [cereal](https://uscilab.github.io/cereal/). With cista, I would recommend using `cista::raw::string`, etc.

If you want to write a custom serializer for `std::` data structures, you might want to look into this:
https://github.com/felixguendling/cista/blob/master/test/std_vector_test.cc

**Comment by dotkt** [comment]
thank you very much.
