### ISSUE TITLE
Serialization of hash maps/sets in structs?

### ISSUE THREAD

**Issue by IrisChase** [felixguendling/cista#88]
This is concerning https://github.com/felixguendling/cista/wiki/Installation-and-Usage#basic-usage

Specifically "more types such as map/set/etc. may follow"

Does this mean that structs containing `cista::offset::hash_map<T, T2>` aren't able to be serialized automatically? I'm also wondering if this statement is up to date.

**Comment by felixguendling** [comment]
Hashmap ist working as intended. You can try it out :-)
