### ISSUE TITLE
_MSC_VER not defined in msys(mingw64) and cista doesn't compile

### ISSUE THREAD

**Issue by ComradeStalin17** [felixguendling/cista#89]
On windows with msys(mingw64) very strange behavior occurs. Cista tries include linux headers on windows and file.h uses linux implementation. I replace _MSC_VER with _WIN32 and and changed the compile conditions a little in many places and cista started to work well. I'm not sure that I did well, but it works.

**Comment by felixguendling** [comment]
Can you please make you pull request with your changes?

**Comment by ComradeStalin17** [comment]
I apologize for the long delay in reply. I created a pull request. Also, when using mmap with the modify flag, an exception is thrown : "open file mode not supported" in function "open_file".
