### ISSUE TITLE
Arity will fail for PODs with only one field

### ISSUE THREAD

**Issue by ChemiaAion** [felixguendling/cista#9]
Hi,

I have heavily tested [Björn Fahller's](https://playfulprogramming.blogspot.com/2016/12/serializing-structs-with-c17-structured.html) arity approach used here and I found that **(...)MAKE_ARITY_FUNC(1)** will fail for simple one-field PODs such as: `struct Field1 { int number1; };`

It's because **is_paren_constructible** would be true in such a case (count = 1), here:
https://github.com/felixguendling/cista/blob/e25935a817d34c08e3bce32eb64935fcfad300a4/include/cista/reflection/arity.h#L62

IMHO **(...)MAKE_ARITY_FUNC(1)** should be considered as a _special case_, e.g. without **is_paren_constructible** at all or as for a sake of template **is_paren_constructible<T, count>()** (with negation removed).

**Comment by felixguendling** [comment]
Thank you very much for sharing this!

I have removed `is_paren_constructible` for one-field PODs. See PR #10:
Commit: https://github.com/felixguendling/cista/pull/10/commits/f40a538079e374d5032476bfc8ea5613a7dfe88a#diff-1b0d553d1c8fa80aaa46529c069c9deeR67

It's working in the Linux CI & Windows CI.
